-- ============================================================================
-- MDC Validation System - Populate Configuration Table (CAPS Schema)
-- ============================================================================
-- Purpose: Insert configuration data for all CAPS schema tables
-- Note: Email addresses are placeholders - update manually with actual emails
-- ============================================================================

-- FAD (Foster/Adoptive Development) Tables
INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, COMPARE_TO_TABLE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'FAD_SUM', 'ROW_COUNT', 'Y', 'FAD_FACT', 10, 'analyst1@example.com', 'Should match FAD_FACT count exactly', 'HIGH');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'FAD_SUM', 'COLUMN_COUNT', 'Y', 10, 'analyst1@example.com', 'HIGH');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, COMPARE_TO_TABLE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'FAD_FACT', 'ROW_COUNT', 'Y', 'FAD_SUM', 10, 'analyst1@example.com', 'Should match FAD_SUM count exactly', 'HIGH');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'FAD_FACT', 'COLUMN_COUNT', 'Y', 10, 'analyst1@example.com', 'HIGH');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, COMPARE_TO_TABLE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'FAD_INTERESTS_DIM', 'ROW_COUNT', 'Y', 'FAD_SUM', 10, 'analyst1@example.com', 'Should match both FAD_SUM and FAD_FACT counts', 'HIGH');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'FAD_INTERESTS_DIM', 'COLUMN_COUNT', 'Y', 10, 'analyst1@example.com', 'HIGH');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'FAD_PRINC_DIM', 'ROW_COUNT', 'Y', 10, 'analyst1@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'FAD_PRINC_DIM', 'COLUMN_COUNT', 'Y', 10, 'analyst1@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'FAD_TRAINING_DIM', 'ROW_COUNT', 'Y', 10, 'analyst1@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'FAD_TRAINING_DIM', 'COLUMN_COUNT', 'Y', 10, 'analyst1@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'FAD_WORKER_DIM', 'ROW_COUNT', 'Y', 10, 'analyst1@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'FAD_WORKER_DIM', 'COLUMN_COUNT', 'Y', 10, 'analyst1@example.com', 'MEDIUM');

-- FCL (Family and Children's Legal) Tables
INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, GROUP_BY_COLUMNS, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'FCL_PMC_CHILD', 'ROW_COUNT', 'Y', 'id_pp_person', 2, 'analyst2@example.com', 'Change > 2% up/down may need investigation. December months may have > 2% change (holiday time off, adoption month). Exits bounce around but there will always be SOME exits.', 'HIGH');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'FCL_PMC_CHILD', 'COLUMN_COUNT', 'Y', 2, 'analyst2@example.com', 'HIGH');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, GROUP_BY_COLUMNS, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'FCL_PMC_CHILD_PLCMT', 'ROW_COUNT', 'Y', 'id_pp_person,ID_SA_PLCMT_EVENT', 3, 'analyst2@example.com', 'Row count may not match other counts (children with no placement event). Count of PIDs should match fcl_pmc_child count. Change of 3% up or down may need research.', 'HIGH');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'FCL_PMC_CHILD_PLCMT', 'COLUMN_COUNT', 'Y', 3, 'analyst2@example.com', 'HIGH');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, GROUP_BY_COLUMNS, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'FCL_13_TMC_CHILD_PLCMT', 'ROW_COUNT', 'Y', 'id_pp_person,ID_SA_PLCMT_EVENT', 3, 'analyst2@example.com', 'Similar to FCL_PMC_CHILD_PLCMT', 'HIGH');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'FCL_13_TMC_CHILD_PLCMT', 'COLUMN_COUNT', 'Y', 3, 'analyst2@example.com', 'HIGH');

-- FPS (Family Preservation Services) Tables
INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'FPS_REG_SUM', 'ROW_COUNT', 'Y', 10, 'analyst3@example.com', 'Multiple dt_load_process values due to 14-month refresh cycle. Recommended: group by id_time_load only.', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'FPS_REG_SUM', 'COLUMN_COUNT', 'Y', 10, 'analyst3@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'FPS_CNTY_SUM', 'ROW_COUNT', 'Y', 10, 'analyst3@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'FPS_CNTY_SUM', 'COLUMN_COUNT', 'Y', 10, 'analyst3@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'FPS_CNTY_TAB_SUM', 'ROW_COUNT', 'Y', 10, 'analyst3@example.com', 'Seems to have current time_load and each October', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'FPS_CNTY_TAB_SUM', 'COLUMN_COUNT', 'Y', 10, 'analyst3@example.com', 'MEDIUM');

-- FAM (Family) Tables
INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'FAM_PRINC_SUM', 'ROW_COUNT', 'Y', 10, 'analyst4@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'FAM_PRINC_SUM', 'COLUMN_COUNT', 'Y', 10, 'analyst4@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, COMPARE_TO_TABLE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'FAM_SUM', 'ROW_COUNT', 'Y', 'FAM_FACT', 10, 'analyst4@example.com', 'Should match FAM_FACT', 'HIGH');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'FAM_SUM', 'COLUMN_COUNT', 'Y', 10, 'analyst4@example.com', 'HIGH');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, COMPARE_TO_TABLE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'FAM_FACT', 'ROW_COUNT', 'Y', 'FAM_SUM', 10, 'analyst4@example.com', 'Should match FAM_SUM', 'HIGH');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'FAM_FACT', 'COLUMN_COUNT', 'Y', 10, 'analyst4@example.com', 'HIGH');

-- PAL (Permanency Assistance Legal) Tables
INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'PAL_SUM', 'ROW_COUNT', 'Y', 10, 'analyst5@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'PAL_SUM', 'COLUMN_COUNT', 'Y', 10, 'analyst5@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, COMPARE_TO_TABLE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'PAL_FACT', 'ROW_COUNT', 'Y', 'PAL_SUM', 10, 'analyst5@example.com', 'Won''t be exact match with PAL_SUM, should be within range', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'PAL_FACT', 'COLUMN_COUNT', 'Y', 10, 'analyst5@example.com', 'MEDIUM');

-- SA (Substitute Care) Tables
INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'SAW_SUM', 'ROW_COUNT', 'Y', 10, 'analyst6@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'SAW_SUM', 'COLUMN_COUNT', 'Y', 10, 'analyst6@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, COMPARE_TO_TABLE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'SA_SUM', 'ROW_COUNT', 'Y', 'SA_SUBCARE_FACT', 10, 'analyst6@example.com', 'Should match SA_SUBCARE_FACT count exactly', 'HIGH');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'SA_SUM', 'COLUMN_COUNT', 'Y', 10, 'analyst6@example.com', 'HIGH');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, COMPARE_TO_TABLE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'SA_SUBCARE_FACT', 'ROW_COUNT', 'Y', 'SA_SUM', 10, 'analyst6@example.com', 'Should match SA_SUM count exactly', 'HIGH');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'SA_SUBCARE_FACT', 'COLUMN_COUNT', 'Y', 10, 'analyst6@example.com', 'HIGH');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'SA_PLCMT_HIST_DIM', 'ROW_COUNT', 'Y', 10, 'analyst6@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'SA_PLCMT_HIST_DIM', 'COLUMN_COUNT', 'Y', 10, 'analyst6@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'SA_PLACEMENT_DIM', 'ROW_COUNT', 'Y', 10, 'analyst6@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'SA_PLACEMENT_DIM', 'COLUMN_COUNT', 'Y', 10, 'analyst6@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'SA_WORKLOAD_FACT', 'ROW_COUNT', 'Y', 10, 'analyst6@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'SA_WORKLOAD_FACT', 'COLUMN_COUNT', 'Y', 10, 'analyst6@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'SA_PERS_SVC_PKG_HIST_DIM', 'ROW_COUNT', 'Y', 10, 'analyst6@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'SA_PERS_SVC_PKG_HIST_DIM', 'COLUMN_COUNT', 'Y', 10, 'analyst6@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'SA_PERS_ADDON_SVC_PKG_HIST_DIM', 'ROW_COUNT', 'Y', 10, 'analyst6@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'SA_PERS_ADDON_SVC_PKG_HIST_DIM', 'COLUMN_COUNT', 'Y', 10, 'analyst6@example.com', 'MEDIUM');

COMMIT;

PROMPT CAPS schema configuration data inserted successfully.

