-- ============================================================================
-- MDC Validation System - Populate Configuration Table (CAPS Schema - Remaining)
-- ============================================================================
-- Purpose: Insert configuration data for remaining CAPS schema tables
--          (HIST, Metric, ICPC, TARE, APS, CSL, PCS/CHL/CMN, INT/CALL, Other)
-- Note: Email addresses are placeholders - update manually with actual emails
-- ============================================================================

-- HIST (Historical) Tables
INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'CSA_EPISODE_HIST_FACT', 'ROW_COUNT', 'Y', 10, 'analyst7@example.com', 'HIST table - different time load ranges', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'CSA_EPISODE_HIST_FACT', 'COLUMN_COUNT', 'Y', 10, 'analyst7@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'SXV_HIST_DIM', 'ROW_COUNT', 'Y', 10, 'analyst7@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'SXV_HIST_DIM', 'COLUMN_COUNT', 'Y', 10, 'analyst7@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'VC_NOTF_HIST_DIM', 'ROW_COUNT', 'Y', 10, 'analyst7@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'VC_NOTF_HIST_DIM', 'COLUMN_COUNT', 'Y', 10, 'analyst7@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'TRAFFICKING_HIST_DIM', 'ROW_COUNT', 'Y', 10, 'analyst7@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'TRAFFICKING_HIST_DIM', 'COLUMN_COUNT', 'Y', 10, 'analyst7@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'MSNG_CHILD_HIST_DIM', 'ROW_COUNT', 'Y', 10, 'analyst7@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'MSNG_CHILD_HIST_DIM', 'COLUMN_COUNT', 'Y', 10, 'analyst7@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'MSNG_CHILD_RCVRY_HIST_DIM', 'ROW_COUNT', 'Y', 10, 'analyst7@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'MSNG_CHILD_RCVRY_HIST_DIM', 'COLUMN_COUNT', 'Y', 10, 'analyst7@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'PCSP_FACT', 'ROW_COUNT', 'Y', 10, 'analyst7@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'PCSP_FACT', 'COLUMN_COUNT', 'Y', 10, 'analyst7@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'RISK_REASMNT_HIST_DIM', 'ROW_COUNT', 'Y', 10, 'analyst7@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'RISK_REASMNT_HIST_DIM', 'COLUMN_COUNT', 'Y', 10, 'analyst7@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'CPS_RA_HIST_DIM', 'ROW_COUNT', 'Y', 10, 'analyst7@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'CPS_RA_HIST_DIM', 'COLUMN_COUNT', 'Y', 10, 'analyst7@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'FP_HIST_DIM', 'ROW_COUNT', 'Y', 10, 'analyst7@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'FP_HIST_DIM', 'COLUMN_COUNT', 'Y', 10, 'analyst7@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'FP_PARTCPNT_HIST_DIM', 'ROW_COUNT', 'Y', 10, 'analyst7@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'FP_PARTCPNT_HIST_DIM', 'COLUMN_COUNT', 'Y', 10, 'analyst7@example.com', 'MEDIUM');

-- Metric Tables
INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, GROUP_BY_COLUMNS, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'MTR_TREND_MNTH_SUM', 'ROW_COUNT', 'Y', 'metric_type', 10, 'analyst8@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'MTR_TREND_MNTH_SUM', 'COLUMN_COUNT', 'Y', 10, 'analyst8@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, GROUP_BY_COLUMNS, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'MTR_TREND_FY_HIST_SUM', 'ROW_COUNT', 'Y', 'metric_type', 10, 'analyst8@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'MTR_TREND_FY_HIST_SUM', 'COLUMN_COUNT', 'Y', 10, 'analyst8@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, GROUP_BY_COLUMNS, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'MTR_TRENDING_SUM', 'ROW_COUNT', 'Y', 'metric_type', 10, 'analyst8@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'MTR_TRENDING_SUM', 'COLUMN_COUNT', 'Y', 10, 'analyst8@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, GROUP_BY_COLUMNS, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'MTR_TREND_WRK_MNTH_SUM', 'ROW_COUNT', 'Y', 'metric_type', 10, 'analyst8@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'MTR_TREND_WRK_MNTH_SUM', 'COLUMN_COUNT', 'Y', 10, 'analyst8@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, GROUP_BY_COLUMNS, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'MTR_TREND_WRK_FY_HIST_SUM', 'ROW_COUNT', 'Y', 'metric_type', 10, 'analyst8@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'MTR_TREND_WRK_FY_HIST_SUM', 'COLUMN_COUNT', 'Y', 10, 'analyst8@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, GROUP_BY_COLUMNS, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'MTR_TRENDING_WRK_SUM', 'ROW_COUNT', 'Y', 'metric_type', 10, 'analyst8@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'MTR_TRENDING_WRK_SUM', 'COLUMN_COUNT', 'Y', 10, 'analyst8@example.com', 'MEDIUM');

-- ICPC (Interstate Compact on Placement of Children) Tables
INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'ICPC_DOCUMENT_HIST_FACT', 'ROW_COUNT', 'Y', 10, 'analyst9@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'ICPC_DOCUMENT_HIST_FACT', 'COLUMN_COUNT', 'Y', 10, 'analyst9@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'ICPC_RQST_HIST_FACT', 'ROW_COUNT', 'Y', 10, 'analyst9@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'ICPC_RQST_HIST_FACT', 'COLUMN_COUNT', 'Y', 10, 'analyst9@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'ICPC_STAT_HIST_FACT', 'ROW_COUNT', 'Y', 10, 'analyst9@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'ICPC_STAT_HIST_FACT', 'COLUMN_COUNT', 'Y', 10, 'analyst9@example.com', 'MEDIUM');

-- TARE (Texas Abuse Registry Enterprise) Tables
INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'TARE_CHILD_CHAR_SUM', 'ROW_COUNT', 'Y', 10, 'analyst10@example.com', 'Time load >= 100368', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'TARE_CHILD_CHAR_SUM', 'COLUMN_COUNT', 'Y', 10, 'analyst10@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'TARE_CHILD_SUM', 'ROW_COUNT', 'Y', 10, 'analyst10@example.com', 'Time load >= 100368', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'TARE_CHILD_SUM', 'COLUMN_COUNT', 'Y', 10, 'analyst10@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'TARE_FAMILY_SUM', 'ROW_COUNT', 'Y', 10, 'analyst10@example.com', 'Time load >= 100368', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'TARE_FAMILY_SUM', 'COLUMN_COUNT', 'Y', 10, 'analyst10@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'TARE_INQUIRY_SUM', 'ROW_COUNT', 'Y', 10, 'analyst10@example.com', 'Time load >= 100368', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'TARE_INQUIRY_SUM', 'COLUMN_COUNT', 'Y', 10, 'analyst10@example.com', 'MEDIUM');

-- APS (Adult Protective Services) Tables
INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'APS_ASMT_HIST_FACT', 'ROW_COUNT', 'Y', 10, 'analyst11@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'APS_ASMT_HIST_FACT', 'COLUMN_COUNT', 'Y', 10, 'analyst11@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'APS_ASMT_RORAFLW_HIST_DIM', 'ROW_COUNT', 'Y', 10, 'analyst11@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'APS_ASMT_RORAFLW_HIST_DIM', 'COLUMN_COUNT', 'Y', 10, 'analyst11@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'APS_ASMT_RSPNS_HIST_DIM', 'ROW_COUNT', 'Y', 10, 'analyst11@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'APS_ASMT_RSPNS_HIST_DIM', 'COLUMN_COUNT', 'Y', 10, 'analyst11@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'APS_SP_MNTRNG_HIST_DIM', 'ROW_COUNT', 'Y', 10, 'analyst11@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'APS_SP_MNTRNG_HIST_DIM', 'COLUMN_COUNT', 'Y', 10, 'analyst11@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'APS_SP_PROB_ACTN_HIST_DIM', 'ROW_COUNT', 'Y', 10, 'analyst11@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'APS_SP_PROB_ACTN_HIST_DIM', 'COLUMN_COUNT', 'Y', 10, 'analyst11@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'APS_SRVC_PLAN_HIST_FACT', 'ROW_COUNT', 'Y', 10, 'analyst11@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'APS_SRVC_PLAN_HIST_FACT', 'COLUMN_COUNT', 'Y', 10, 'analyst11@example.com', 'MEDIUM');

-- CSL (Child Safety Licensing) Tables
INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'CSL_SUM', 'ROW_COUNT', 'Y', 10, 'analyst12@example.com', 'Time load >= 100356', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'CSL_SUM', 'COLUMN_COUNT', 'Y', 10, 'analyst12@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'CSL_AVG_REG_CNTY_SUM', 'ROW_COUNT', 'Y', 10, 'analyst12@example.com', 'Time load >= 100356', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'CSL_AVG_REG_CNTY_SUM', 'COLUMN_COUNT', 'Y', 10, 'analyst12@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'CSL_DAILY_KIN_WRKR_SUM', 'ROW_COUNT', 'Y', 10, 'analyst12@example.com', 'Time load >= 100356', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'CSL_DAILY_KIN_WRKR_SUM', 'COLUMN_COUNT', 'Y', 10, 'analyst12@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'CSL_DAILY_LSP_WRKR_SUM', 'ROW_COUNT', 'Y', 10, 'analyst12@example.com', 'Time load >= 100356', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'CSL_DAILY_LSP_WRKR_SUM', 'COLUMN_COUNT', 'Y', 10, 'analyst12@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'CSL_DAILY_SFI_WRKR_SUM', 'ROW_COUNT', 'Y', 10, 'analyst12@example.com', 'Time load >= 100356', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'CSL_DAILY_SFI_WRKR_SUM', 'COLUMN_COUNT', 'Y', 10, 'analyst12@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'CSL_DAILY_WKLD_SUM', 'ROW_COUNT', 'Y', 10, 'analyst12@example.com', 'Time load >= 100356', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'CSL_DAILY_WKLD_SUM', 'COLUMN_COUNT', 'Y', 10, 'analyst12@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'CSL_DAILY_WORKER_SUM', 'ROW_COUNT', 'Y', 10, 'analyst12@example.com', 'Time load >= 100356', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'CSL_DAILY_WORKER_SUM', 'COLUMN_COUNT', 'Y', 10, 'analyst12@example.com', 'MEDIUM');

COMMIT;

PROMPT Remaining CAPS schema configuration data inserted successfully.

