-- ============================================================================
-- MDC Validation System - Populate Configuration Table (CAPS Schema - Final)
-- ============================================================================
-- Purpose: Insert configuration data for remaining CAPS tables
--          (PCS/CHL/CMN, INT/CALL, Other tables)
-- Note: Email addresses are placeholders - update manually with actual emails
-- ============================================================================

-- PCS/CHL/CMN (Permanency Care Services/Child/Common) Tables
INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'PCS_CNTRTR_SFTY_ALLEG_SUM', 'ROW_COUNT', 'Y', 10, 'analyst13@example.com', 'Time load >= 100368', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'PCS_CNTRTR_SFTY_ALLEG_SUM', 'COLUMN_COUNT', 'Y', 10, 'analyst13@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'PCS_CNTRTR_SFTY_SUM', 'ROW_COUNT', 'Y', 10, 'analyst13@example.com', 'Time load >= 100368', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'PCS_CNTRTR_SFTY_SUM', 'COLUMN_COUNT', 'Y', 10, 'analyst13@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'PCS_DAILY_SBLNG_SUM', 'ROW_COUNT', 'Y', 10, 'analyst13@example.com', 'Time load >= 100368', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'PCS_DAILY_SBLNG_SUM', 'COLUMN_COUNT', 'Y', 10, 'analyst13@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'PCS_PLCMT_SUM', 'ROW_COUNT', 'Y', 10, 'analyst13@example.com', 'Time load >= 100368', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'PCS_PLCMT_SUM', 'COLUMN_COUNT', 'Y', 10, 'analyst13@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'CHL_DAILY_WORKER_SUM', 'ROW_COUNT', 'Y', 10, 'analyst13@example.com', 'Time load >= 100368', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'CHL_DAILY_WORKER_SUM', 'COLUMN_COUNT', 'Y', 10, 'analyst13@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, GROUP_BY_COLUMNS, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'CMN_CONTACT_APS_SUM', 'ROW_COUNT', 'Y', 'cd_stage_program', 10, 'analyst13@example.com', 'Time load >= 100368', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'CMN_CONTACT_APS_SUM', 'COLUMN_COUNT', 'Y', 10, 'analyst13@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'CMN_CONTACT_CPS_HIST_DIM', 'ROW_COUNT', 'Y', 10, 'analyst13@example.com', 'Time load >= 100368', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'CMN_CONTACT_CPS_HIST_DIM', 'COLUMN_COUNT', 'Y', 10, 'analyst13@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'CMN_CONTACT_CPS_SUM', 'ROW_COUNT', 'Y', 10, 'analyst13@example.com', 'Time load >= 100368', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'CMN_CONTACT_CPS_SUM', 'COLUMN_COUNT', 'Y', 10, 'analyst13@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'CMN_FGDM_SUM', 'ROW_COUNT', 'Y', 10, 'analyst13@example.com', 'Time load >= 100368', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'CMN_FGDM_SUM', 'COLUMN_COUNT', 'Y', 10, 'analyst13@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'CMN_PCSP_SUM', 'ROW_COUNT', 'Y', 10, 'analyst13@example.com', 'Time load >= 100368', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'CMN_PCSP_SUM', 'COLUMN_COUNT', 'Y', 10, 'analyst13@example.com', 'MEDIUM');

-- INT/CALL (Intake/Call) Tables
INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'CALL_SUM', 'ROW_COUNT', 'Y', 10, 'analyst14@example.com', 'Time load >= 100368', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'CALL_SUM', 'COLUMN_COUNT', 'Y', 10, 'analyst14@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, GROUP_BY_COLUMNS, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'INT_SUM', 'ROW_COUNT', 'Y', 'cd_program', 10, 'analyst14@example.com', 'Time load >= 100368', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'INT_SUM', 'COLUMN_COUNT', 'Y', 10, 'analyst14@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'INT_AFC_FACT', 'ROW_COUNT', 'Y', 10, 'analyst14@example.com', 'Time load >= 100368', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'INT_AFC_FACT', 'COLUMN_COUNT', 'Y', 10, 'analyst14@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'INT_APS_FACT', 'ROW_COUNT', 'Y', 10, 'analyst14@example.com', 'Time load >= 100368', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'INT_APS_FACT', 'COLUMN_COUNT', 'Y', 10, 'analyst14@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'INT_CALL_FACT', 'ROW_COUNT', 'Y', 10, 'analyst14@example.com', 'Time load >= 100368', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'INT_CALL_FACT', 'COLUMN_COUNT', 'Y', 10, 'analyst14@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'INT_LIC_FACT', 'ROW_COUNT', 'Y', 10, 'analyst14@example.com', 'Time load >= 100368', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'INT_LIC_FACT', 'COLUMN_COUNT', 'Y', 10, 'analyst14@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'INT_CASE_SPC_FACT', 'ROW_COUNT', 'Y', 10, 'analyst14@example.com', 'Time load >= 100368', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'INT_CASE_SPC_FACT', 'COLUMN_COUNT', 'Y', 10, 'analyst14@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'INT_CPS_FACT', 'ROW_COUNT', 'Y', 10, 'analyst14@example.com', 'Time load >= 100368', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'INT_CPS_FACT', 'COLUMN_COUNT', 'Y', 10, 'analyst14@example.com', 'MEDIUM');

-- Other CAPS Tables
INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, GROUP_BY_COLUMNS, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'SVC_SUM', 'ROW_COUNT', 'Y', 'cd_svc_type', 10, 'analyst15@example.com', 'Time load >= 100368', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'SVC_SUM', 'COLUMN_COUNT', 'Y', 10, 'analyst15@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, GROUP_BY_COLUMNS, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'CASE_READ_SUM', 'ROW_COUNT', 'Y', 'cd_program', 10, 'analyst15@example.com', 'Time load >= 100368', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'CASE_READ_SUM', 'COLUMN_COUNT', 'Y', 10, 'analyst15@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'CASE_IMAGE_AUDIT_SUM', 'ROW_COUNT', 'Y', 10, 'analyst15@example.com', 'Time load >= 100368', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'CASE_IMAGE_AUDIT_SUM', 'COLUMN_COUNT', 'Y', 10, 'analyst15@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'PP_SUM', 'ROW_COUNT', 'Y', 10, 'analyst15@example.com', 'Time load >= 100356', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'PP_SUM', 'COLUMN_COUNT', 'Y', 10, 'analyst15@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'PP_LEGAL_CUST_FACT', 'ROW_COUNT', 'Y', 10, 'analyst15@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'PP_LEGAL_CUST_FACT', 'COLUMN_COUNT', 'Y', 10, 'analyst15@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'SVC_AOC_FACT', 'ROW_COUNT', 'Y', 10, 'analyst15@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'SVC_AOC_FACT', 'COLUMN_COUNT', 'Y', 10, 'analyst15@example.com', 'MEDIUM');

-- AFCARS Tables
INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, GROUP_BY_COLUMNS, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'AFCARS_ADO_FACT', 'ROW_COUNT', 'Y', 'nbr_federal_year,cd_federal_period', 10, 'analyst16@example.com', 'Time load >= 100356', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'AFCARS_ADO_FACT', 'COLUMN_COUNT', 'Y', 10, 'analyst16@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, GROUP_BY_COLUMNS, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'AFCARS_ADO_SUBMIT', 'ROW_COUNT', 'Y', 'nbr_federal_year,cd_federal_period', 10, 'analyst16@example.com', 'Time load >= 100356', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'AFCARS_ADO_SUBMIT', 'COLUMN_COUNT', 'Y', 10, 'analyst16@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, GROUP_BY_COLUMNS, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'AFCARS_FC_FACT', 'ROW_COUNT', 'Y', 'nbr_federal_year,cd_federal_period', 10, 'analyst16@example.com', 'Time load >= 100356', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'AFCARS_FC_FACT', 'COLUMN_COUNT', 'Y', 10, 'analyst16@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, GROUP_BY_COLUMNS, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'AFCARS_FC_SUBMIT', 'ROW_COUNT', 'Y', 'nbr_federal_year,cd_federal_period', 10, 'analyst16@example.com', 'Time load >= 100356', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'AFCARS_FC_SUBMIT', 'COLUMN_COUNT', 'Y', 10, 'analyst16@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, GROUP_BY_COLUMNS, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'AFCARS_CFSR_SUM', 'ROW_COUNT', 'Y', 'cd_federal_period', 10, 'analyst16@example.com', 'Time load >= 100356', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'AFCARS_CFSR_SUM', 'COLUMN_COUNT', 'Y', 10, 'analyst16@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, GROUP_BY_COLUMNS, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'AFCARS_FC_FTF_CNT_SUM', 'ROW_COUNT', 'Y', 'cd_federal_period', 10, 'analyst16@example.com', 'Time load >= 100356', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'AFCARS_FC_FTF_CNT_SUM', 'COLUMN_COUNT', 'Y', 10, 'analyst16@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, GROUP_BY_COLUMNS, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'NCANDS_FACT', 'ROW_COUNT', 'Y', 'NBR_SUBYR_F', 10, 'analyst16@example.com', 'Time load >= 100356', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'NCANDS_FACT', 'COLUMN_COUNT', 'Y', 10, 'analyst16@example.com', 'MEDIUM');

-- FN (Family Network) Tables
INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'FN_ACT_CNTRCTS_FACT', 'ROW_COUNT', 'Y', 10, 'analyst17@example.com', 'Time load >= 100356', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'FN_ACT_CNTRCTS_FACT', 'COLUMN_COUNT', 'Y', 10, 'analyst17@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'FN_ACT_CNTRCTS_HIST_FACT', 'ROW_COUNT', 'Y', 10, 'analyst17@example.com', 'Time load >= 100356', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'FN_ACT_CNTRCTS_HIST_FACT', 'COLUMN_COUNT', 'Y', 10, 'analyst17@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'FN_ADMIN_DLVRD_HIST_FACT', 'ROW_COUNT', 'Y', 10, 'analyst17@example.com', 'Time load >= 100356', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'FN_ADMIN_DLVRD_HIST_FACT', 'COLUMN_COUNT', 'Y', 10, 'analyst17@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'FN_APS_SVCAUTH_APRV_SUM', 'ROW_COUNT', 'Y', 10, 'analyst17@example.com', 'Time load >= 100356', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'FN_APS_SVCAUTH_APRV_SUM', 'COLUMN_COUNT', 'Y', 10, 'analyst17@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'FN_AS_HIST_SUM', 'ROW_COUNT', 'Y', 10, 'analyst17@example.com', 'Time load >= 100356', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'FN_AS_HIST_SUM', 'COLUMN_COUNT', 'Y', 10, 'analyst17@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'FN_CONTRACTS_HIST_FACT', 'ROW_COUNT', 'Y', 10, 'analyst17@example.com', 'Time load >= 100356', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'FN_CONTRACTS_HIST_FACT', 'COLUMN_COUNT', 'Y', 10, 'analyst17@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'FN_FC_HIST_SUM', 'ROW_COUNT', 'Y', 10, 'analyst17@example.com', 'Time load >= 100356', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'FN_FC_HIST_SUM', 'COLUMN_COUNT', 'Y', 10, 'analyst17@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'FN_SRVC_AUTH_HIST_FACT', 'ROW_COUNT', 'Y', 10, 'analyst17@example.com', 'Time load >= 100356', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'FN_SRVC_AUTH_HIST_FACT', 'COLUMN_COUNT', 'Y', 10, 'analyst17@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'FN_SVCAUTH_APRV_HIST_FACT', 'ROW_COUNT', 'Y', 10, 'analyst17@example.com', 'Time load >= 100356', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'FN_SVCAUTH_APRV_HIST_FACT', 'COLUMN_COUNT', 'Y', 10, 'analyst17@example.com', 'MEDIUM');

COMMIT;

PROMPT Final CAPS schema configuration data inserted successfully.

