-- ============================================================================
-- MDC Validation System - Populate Configuration Table (CCL Schema)
-- ============================================================================
-- Purpose: Insert configuration data for all CCL schema tables
-- Note: Email addresses are placeholders - update manually with actual emails
-- Note: Most CCL tables have time load >= 100368 and use dt_load_process grouping
-- ============================================================================

-- Facility Tables
INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, COMPARE_TO_TABLE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'FACILITY_FACT', 'ROW_COUNT', 'Y', 'CCL_FACILITY_SUM', 10, 'analyst18@example.com', 'Should match CCL_FACILITY_SUM for all time loads >= 100261', 'HIGH');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'FACILITY_FACT', 'COLUMN_COUNT', 'Y', 10, 'analyst18@example.com', 'HIGH');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, COMPARE_TO_TABLE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'CCL_FACILITY_SUM', 'ROW_COUNT', 'Y', 'FACILITY_FACT', 10, 'analyst18@example.com', 'Should match FACILITY_FACT for all time loads >= 100261', 'HIGH');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'CCL_FACILITY_SUM', 'COLUMN_COUNT', 'Y', 10, 'analyst18@example.com', 'HIGH');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'FACILITY_HIST_FACT', 'ROW_COUNT', 'Y', 10, 'analyst18@example.com', 'Time load >= 100368', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'FACILITY_HIST_FACT', 'COLUMN_COUNT', 'Y', 10, 'analyst18@example.com', 'MEDIUM');

-- Investigation Tables
INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'INV_HIST_FACT', 'ROW_COUNT', 'Y', 10, 'analyst19@example.com', 'Time load >= 100368', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'INV_HIST_FACT', 'COLUMN_COUNT', 'Y', 10, 'analyst19@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'INV_FACT', 'ROW_COUNT', 'Y', 10, 'analyst19@example.com', 'Time load >= 100368', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'INV_FACT', 'COLUMN_COUNT', 'Y', 10, 'analyst19@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'CCL_INV_SUM', 'ROW_COUNT', 'Y', 10, 'analyst19@example.com', 'Time load >= 100368', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'CCL_INV_SUM', 'COLUMN_COUNT', 'Y', 10, 'analyst19@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'INTAKE_FACT', 'ROW_COUNT', 'Y', 10, 'analyst19@example.com', 'Time load >= 100368', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'INTAKE_FACT', 'COLUMN_COUNT', 'Y', 10, 'analyst19@example.com', 'MEDIUM');

-- Inspection Tables
INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'INSP_FACT', 'ROW_COUNT', 'Y', 10, 'analyst20@example.com', 'Time load >= 100368', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'INSP_FACT', 'COLUMN_COUNT', 'Y', 10, 'analyst20@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'INSP_HIST_FACT', 'ROW_COUNT', 'Y', 10, 'analyst20@example.com', 'Time load >= 100368', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'INSP_HIST_FACT', 'COLUMN_COUNT', 'Y', 10, 'analyst20@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'CCL_INSP_SUM', 'ROW_COUNT', 'Y', 10, 'analyst20@example.com', 'Time load >= 100368', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'CCL_INSP_SUM', 'COLUMN_COUNT', 'Y', 10, 'analyst20@example.com', 'MEDIUM');

-- Waiver Tables
INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'WAIVER_FACT', 'ROW_COUNT', 'Y', 10, 'analyst21@example.com', 'Time load >= 100368', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'WAIVER_FACT', 'COLUMN_COUNT', 'Y', 10, 'analyst21@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'WAIVER_HIST_FACT', 'ROW_COUNT', 'Y', 10, 'analyst21@example.com', 'Time load >= 100368', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'WAIVER_HIST_FACT', 'COLUMN_COUNT', 'Y', 10, 'analyst21@example.com', 'MEDIUM');

-- Background Check Tables
INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'BKGRND_CHK_HIST_DIM', 'ROW_COUNT', 'Y', 10, 'analyst22@example.com', 'Time load >= 100368', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'BKGRND_CHK_HIST_DIM', 'COLUMN_COUNT', 'Y', 10, 'analyst22@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'DPS_CHECK_HIST_DIM', 'ROW_COUNT', 'Y', 10, 'analyst22@example.com', 'Time load >= 100368', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'DPS_CHECK_HIST_DIM', 'COLUMN_COUNT', 'Y', 10, 'analyst22@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'FBI_CHECK_HIST_DIM', 'ROW_COUNT', 'Y', 10, 'analyst22@example.com', 'Time load >= 100368', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'FBI_CHECK_HIST_DIM', 'COLUMN_COUNT', 'Y', 10, 'analyst22@example.com', 'MEDIUM');

-- Corrective Action Tables
INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'CORRV_ACT_HIST_DIM', 'ROW_COUNT', 'Y', 10, 'analyst23@example.com', 'Time load >= 100368', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'CORRV_ACT_HIST_DIM', 'COLUMN_COUNT', 'Y', 10, 'analyst23@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'CA_CORRV_ACT_FACT', 'ROW_COUNT', 'Y', 10, 'analyst23@example.com', 'Time load >= 100368', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'CA_CORRV_ACT_FACT', 'COLUMN_COUNT', 'Y', 10, 'analyst23@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'CNTRL_REG_CHK_HIST_DIM', 'ROW_COUNT', 'Y', 10, 'analyst23@example.com', 'Time load >= 100368', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'CNTRL_REG_CHK_HIST_DIM', 'COLUMN_COUNT', 'Y', 10, 'analyst23@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'CCL_CNTRL_REG_CHK_SUM', 'ROW_COUNT', 'Y', 10, 'analyst23@example.com', 'Time load >= 100368', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'CCL_CNTRL_REG_CHK_SUM', 'COLUMN_COUNT', 'Y', 10, 'analyst23@example.com', 'MEDIUM');

-- Adverse Action Tables
INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'AA_ADVRS_ACT_FACT', 'ROW_COUNT', 'Y', 10, 'analyst24@example.com', 'Time load >= 100368', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'AA_ADVRS_ACT_FACT', 'COLUMN_COUNT', 'Y', 10, 'analyst24@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'ADV_ACT_ASSMNT_DIM', 'ROW_COUNT', 'Y', 10, 'analyst24@example.com', 'Time load >= 100368', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'ADV_ACT_ASSMNT_DIM', 'COLUMN_COUNT', 'Y', 10, 'analyst24@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'ADV_ACT_INSP_DIM', 'ROW_COUNT', 'Y', 10, 'analyst24@example.com', 'Time load >= 100368', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'ADV_ACT_INSP_DIM', 'COLUMN_COUNT', 'Y', 10, 'analyst24@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'ADV_ACT_INV_DIM', 'ROW_COUNT', 'Y', 10, 'analyst24@example.com', 'Time load >= 100368', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'ADV_ACT_INV_DIM', 'COLUMN_COUNT', 'Y', 10, 'analyst24@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'ADVERSE_ACT_HIST_DIM', 'ROW_COUNT', 'Y', 10, 'analyst24@example.com', 'Time load >= 100368', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'ADVERSE_ACT_HIST_DIM', 'COLUMN_COUNT', 'Y', 10, 'analyst24@example.com', 'MEDIUM');

-- Creative Action Tables
INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'CRTV_ACT_INSP_DIM', 'ROW_COUNT', 'Y', 10, 'analyst25@example.com', 'Time load >= 100368', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'CRTV_ACT_INSP_DIM', 'COLUMN_COUNT', 'Y', 10, 'analyst25@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'CRTV_ACT_INV_DIM', 'ROW_COUNT', 'Y', 10, 'analyst25@example.com', 'Time load >= 100368', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'CRTV_ACT_INV_DIM', 'COLUMN_COUNT', 'Y', 10, 'analyst25@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'CRTV_ACT_ASSMNT_DIM', 'ROW_COUNT', 'Y', 10, 'analyst25@example.com', 'Time load >= 100368', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'CRTV_ACT_ASSMNT_DIM', 'COLUMN_COUNT', 'Y', 10, 'analyst25@example.com', 'MEDIUM');

-- Plan Action Tables
INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'PLAN_ACTN_FACT', 'ROW_COUNT', 'Y', 10, 'analyst26@example.com', 'Time load >= 100368', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'PLAN_ACTN_FACT', 'COLUMN_COUNT', 'Y', 10, 'analyst26@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'PLAN_ACTN_INSP_DIM', 'ROW_COUNT', 'Y', 10, 'analyst26@example.com', 'Time load >= 100368', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'PLAN_ACTN_INSP_DIM', 'COLUMN_COUNT', 'Y', 10, 'analyst26@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'PLAN_ACTN_INV_DIM', 'ROW_COUNT', 'Y', 10, 'analyst26@example.com', 'Time load >= 100368', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'PLAN_ACTN_INV_DIM', 'COLUMN_COUNT', 'Y', 10, 'analyst26@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'PLAN_ACTN_ASSMNT_DIM', 'ROW_COUNT', 'Y', 10, 'analyst26@example.com', 'Time load >= 100368', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'PLAN_ACTN_ASSMNT_DIM', 'COLUMN_COUNT', 'Y', 10, 'analyst26@example.com', 'MEDIUM');

-- Monitoring Tables
INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'MONITOR_ASMT_HIST_FACT', 'ROW_COUNT', 'Y', 10, 'analyst27@example.com', 'Time load >= 100368', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'MONITOR_ASMT_HIST_FACT', 'COLUMN_COUNT', 'Y', 10, 'analyst27@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'MA_MNTR_ASMT_FACT', 'ROW_COUNT', 'Y', 10, 'analyst27@example.com', 'Time load >= 100368', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'MA_MNTR_ASMT_FACT', 'COLUMN_COUNT', 'Y', 10, 'analyst27@example.com', 'MEDIUM');

-- Standard Tables
INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'INSP_STNDRD_DIM', 'ROW_COUNT', 'Y', 10, 'analyst28@example.com', 'Time load >= 100368', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'INSP_STNDRD_DIM', 'COLUMN_COUNT', 'Y', 10, 'analyst28@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'INV_STNDRD_DIM', 'ROW_COUNT', 'Y', 10, 'analyst28@example.com', 'Time load >= 100368', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'INV_STNDRD_DIM', 'COLUMN_COUNT', 'Y', 10, 'analyst28@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'MA_STNDRD_DIM', 'ROW_COUNT', 'Y', 10, 'analyst28@example.com', 'Time load >= 100368', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'MA_STNDRD_DIM', 'COLUMN_COUNT', 'Y', 10, 'analyst28@example.com', 'MEDIUM');

-- Other CCL Tables
INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'INV_CONTACT_HIST_DIM', 'ROW_COUNT', 'Y', 10, 'analyst29@example.com', 'Time load >= 100368', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'INV_CONTACT_HIST_DIM', 'COLUMN_COUNT', 'Y', 10, 'analyst29@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'EMP_ASSIGN_DIM', 'ROW_COUNT', 'Y', 10, 'analyst29@example.com', 'Time load >= 100368', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'EMP_ASSIGN_DIM', 'COLUMN_COUNT', 'Y', 10, 'analyst29@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'EMP_HIST_DIM', 'ROW_COUNT', 'Y', 10, 'analyst29@example.com', 'Time load >= 100368', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'EMP_HIST_DIM', 'COLUMN_COUNT', 'Y', 10, 'analyst29@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'PERSON_HIST_DIM', 'ROW_COUNT', 'Y', 10, 'analyst29@example.com', 'Time load >= 100368', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'PERSON_HIST_DIM', 'COLUMN_COUNT', 'Y', 10, 'analyst29@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'PERSON_ALT_HIST_DIM', 'ROW_COUNT', 'Y', 10, 'analyst29@example.com', 'Time load >= 100368', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'PERSON_ALT_HIST_DIM', 'COLUMN_COUNT', 'Y', 10, 'analyst29@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'GOVERNING_BODY_DIM', 'ROW_COUNT', 'Y', 10, 'analyst29@example.com', 'Time load >= 100368', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'GOVERNING_BODY_DIM', 'COLUMN_COUNT', 'Y', 10, 'analyst29@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'INJUNCTION_DIM', 'ROW_COUNT', 'Y', 10, 'analyst29@example.com', 'Time load >= 100368', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'INJUNCTION_DIM', 'COLUMN_COUNT', 'Y', 10, 'analyst29@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'ADMN_PNLTY_FACT', 'ROW_COUNT', 'Y', 10, 'analyst29@example.com', 'Time load >= 100368', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'ADMN_PNLTY_FACT', 'COLUMN_COUNT', 'Y', 10, 'analyst29@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'CCL_DISPLN_ACTN_SUM', 'ROW_COUNT', 'Y', 10, 'analyst29@example.com', 'Time load >= 100368', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'CCL_DISPLN_ACTN_SUM', 'COLUMN_COUNT', 'Y', 10, 'analyst29@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'ALS_NON_KPM_HIST_FACT', 'ROW_COUNT', 'Y', 10, 'analyst29@example.com', 'Time load >= 100368', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CCL', 'ALS_NON_KPM_HIST_FACT', 'COLUMN_COUNT', 'Y', 10, 'analyst29@example.com', 'MEDIUM');

COMMIT;

PROMPT CCL schema configuration data inserted successfully.

