-- ============================================================================
-- MDC Validation System - Populate Configuration Table (SWI Schema)
-- ============================================================================
-- Purpose: Insert configuration data for all SWI schema tables
-- Note: Email addresses are placeholders - update manually with actual emails
-- Note: All SWI tables have time load > 100351
-- ============================================================================

-- AVY (Avery) Tables
INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'SWI', 'AVY_DACTIVITYCODESTAT', 'ROW_COUNT', 'Y', 10, 'analyst30@example.com', 'Time load > 100351', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'SWI', 'AVY_DACTIVITYCODESTAT', 'COLUMN_COUNT', 'Y', 10, 'analyst30@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'SWI', 'AVY_DAPPLICATIONSTAT', 'ROW_COUNT', 'Y', 10, 'analyst30@example.com', 'Time load > 100351', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'SWI', 'AVY_DAPPLICATIONSTAT', 'COLUMN_COUNT', 'Y', 10, 'analyst30@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'SWI', 'AVY_DAGENTBYAPPLICATIONSTAT', 'ROW_COUNT', 'Y', 10, 'analyst30@example.com', 'Time load > 100351', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'SWI', 'AVY_DAGENTBYAPPLICATIONSTAT', 'COLUMN_COUNT', 'Y', 10, 'analyst30@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'SWI', 'AVY_DCALLSIVR', 'ROW_COUNT', 'Y', 10, 'analyst30@example.com', 'Time load > 100351', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'SWI', 'AVY_DCALLSIVR', 'COLUMN_COUNT', 'Y', 10, 'analyst30@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'SWI', 'AVY_MAGENTBYAPPLICATIONSTAT', 'ROW_COUNT', 'Y', 10, 'analyst30@example.com', 'Time load > 100351', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'SWI', 'AVY_MAGENTBYAPPLICATIONSTAT', 'COLUMN_COUNT', 'Y', 10, 'analyst30@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'SWI', 'AVY_MAPPLICATIONSTAT', 'ROW_COUNT', 'Y', 10, 'analyst30@example.com', 'Time load > 100351', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'SWI', 'AVY_MAPPLICATIONSTAT', 'COLUMN_COUNT', 'Y', 10, 'analyst30@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'SWI', 'AVY_MACTIVITYCODESTAT', 'ROW_COUNT', 'Y', 10, 'analyst30@example.com', 'Time load > 100351', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'SWI', 'AVY_MACTIVITYCODESTAT', 'COLUMN_COUNT', 'Y', 10, 'analyst30@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'SWI', 'AVY_MCALLSIVR', 'ROW_COUNT', 'Y', 10, 'analyst30@example.com', 'Time load > 100351', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'SWI', 'AVY_MCALLSIVR', 'COLUMN_COUNT', 'Y', 10, 'analyst30@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'SWI', 'AVY_IAPPLICATIONSTAT', 'ROW_COUNT', 'Y', 10, 'analyst30@example.com', 'Time load > 100351', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'SWI', 'AVY_IAPPLICATIONSTAT', 'COLUMN_COUNT', 'Y', 10, 'analyst30@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'SWI', 'AVY_ICALLSIVR', 'ROW_COUNT', 'Y', 10, 'analyst30@example.com', 'Time load > 100351', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'SWI', 'AVY_ICALLSIVR', 'COLUMN_COUNT', 'Y', 10, 'analyst30@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'SWI', 'AVY_VERINTEVALUATIONS', 'ROW_COUNT', 'Y', 10, 'analyst30@example.com', 'Time load > 100351', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'SWI', 'AVY_VERINTEVALUATIONS', 'COLUMN_COUNT', 'Y', 10, 'analyst30@example.com', 'MEDIUM');

-- SWI Core Tables
INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'SWI', 'SWI_CONTACTS_SUM', 'ROW_COUNT', 'Y', 10, 'analyst31@example.com', 'Time load > 100351', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'SWI', 'SWI_CONTACTS_SUM', 'COLUMN_COUNT', 'Y', 10, 'analyst31@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'SWI', 'SWI_DAILY_CALLS_SUM', 'ROW_COUNT', 'Y', 10, 'analyst31@example.com', 'Time load > 100351', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'SWI', 'SWI_DAILY_CALLS_SUM', 'COLUMN_COUNT', 'Y', 10, 'analyst31@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'SWI', 'SWI_FLOOR_SUM', 'ROW_COUNT', 'Y', 10, 'analyst31@example.com', 'Time load > 100351', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'SWI', 'SWI_FLOOR_SUM', 'COLUMN_COUNT', 'Y', 10, 'analyst31@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'SWI', 'SWI_FY_TOTALS_SUM', 'ROW_COUNT', 'Y', 10, 'analyst31@example.com', 'Time load > 100351', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'SWI', 'SWI_FY_TOTALS_SUM', 'COLUMN_COUNT', 'Y', 10, 'analyst31@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'SWI', 'SWI_INCMG_FACT', 'ROW_COUNT', 'Y', 10, 'analyst31@example.com', 'Time load > 100351', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'SWI', 'SWI_INCMG_FACT', 'COLUMN_COUNT', 'Y', 10, 'analyst31@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'SWI', 'SWI_MNTHLY_CALLS_SUM', 'ROW_COUNT', 'Y', 10, 'analyst31@example.com', 'Time load > 100351', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'SWI', 'SWI_MNTHLY_CALLS_SUM', 'COLUMN_COUNT', 'Y', 10, 'analyst31@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'SWI', 'SWI_SUPV_APPROVAL_FACT', 'ROW_COUNT', 'Y', 10, 'analyst31@example.com', 'Time load > 100351', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'SWI', 'SWI_SUPV_APPROVAL_FACT', 'COLUMN_COUNT', 'Y', 10, 'analyst31@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'SWI', 'SWI_SUPV_SUM', 'ROW_COUNT', 'Y', 10, 'analyst31@example.com', 'Time load > 100351', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'SWI', 'SWI_SUPV_SUM', 'COLUMN_COUNT', 'Y', 10, 'analyst31@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'SWI', 'SWI_SUPV_TYPE_DIM', 'ROW_COUNT', 'Y', 10, 'analyst31@example.com', 'Time load > 100351', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'SWI', 'SWI_SUPV_TYPE_DIM', 'COLUMN_COUNT', 'Y', 10, 'analyst31@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'SWI', 'SWI_WRKR_CONTACTS_SUM', 'ROW_COUNT', 'Y', 10, 'analyst31@example.com', 'Time load > 100351', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'SWI', 'SWI_WRKR_CONTACTS_SUM', 'COLUMN_COUNT', 'Y', 10, 'analyst31@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'SWI', 'SWI_WRKR_SUM', 'ROW_COUNT', 'Y', 10, 'analyst31@example.com', 'Time load > 100351', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'SWI', 'SWI_WRKR_SUM', 'COLUMN_COUNT', 'Y', 10, 'analyst31@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'SWI', 'SWI_WRKR_SUM_TAB', 'ROW_COUNT', 'Y', 10, 'analyst31@example.com', 'Time load > 100351', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'SWI', 'SWI_WRKR_SUM_TAB', 'COLUMN_COUNT', 'Y', 10, 'analyst31@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'SWI', 'SWI_WRKR_TYPE_DIM', 'ROW_COUNT', 'Y', 10, 'analyst31@example.com', 'Time load > 100351', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'SWI', 'SWI_WRKR_TYPE_DIM', 'COLUMN_COUNT', 'Y', 10, 'analyst31@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'SWI', 'SWI_VERINT_EVAL_SUM', 'ROW_COUNT', 'Y', 10, 'analyst31@example.com', 'Time load > 100351', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'SWI', 'SWI_VERINT_EVAL_SUM', 'COLUMN_COUNT', 'Y', 10, 'analyst31@example.com', 'MEDIUM');

COMMIT;

PROMPT SWI schema configuration data inserted successfully.

