-- ============================================================================
-- MDC Validation System - Populate Missing Tables
-- ============================================================================
-- Purpose: Add missing tables found in manual scripts that weren't included
--          in the initial configuration population
-- Note: Email addresses are placeholders - update manually with actual emails
-- ============================================================================

-- INV (Investigation) Tables - Missing from initial config
-- INV_SUM has two validation types: basic with dt_inv_load_process, and grouped by cd_program
INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'INV_SUM', 'ROW_COUNT', 'Y', 10, 'analyst32@example.com', 'Run by program as well. Uses dt_inv_load_process (not dt_load_process). Individual program FACT tables may be much smaller, comparable, or much higher in record count than INV_SUM because INV_SUM tries to narrow the record down to one row for the month in question.', 'HIGH');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, GROUP_BY_COLUMNS, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'INV_SUM', 'ROW_COUNT', 'Y', 'cd_program', 10, 'analyst32@example.com', 'INV_SUM grouped by program. Compare to individual program FACT tables.', 'HIGH');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'INV_SUM', 'COLUMN_COUNT', 'Y', 10, 'analyst32@example.com', 'HIGH');

-- INV program-specific FACT tables
INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'INV_AFC_FACT', 'ROW_COUNT', 'Y', 10, 'analyst32@example.com', 'Uses dt_inv_afc_load_process. Compare to INV_SUM for cd_program=AFC.', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'INV_AFC_FACT', 'COLUMN_COUNT', 'Y', 10, 'analyst32@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'INV_APS_FACT', 'ROW_COUNT', 'Y', 10, 'analyst32@example.com', 'Uses dt_inv_aps_load_process. Compare to INV_SUM for cd_program=APS.', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'INV_APS_FACT', 'COLUMN_COUNT', 'Y', 10, 'analyst32@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'INV_CPS_FACT', 'ROW_COUNT', 'Y', 10, 'analyst32@example.com', 'Uses dt_inv_cps_load_process. Compare to INV_SUM for cd_program=CPS.', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'INV_CPS_FACT', 'COLUMN_COUNT', 'Y', 10, 'analyst32@example.com', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'INV_LIC_FACT', 'ROW_COUNT', 'Y', 10, 'analyst32@example.com', 'Uses dt_inv_lic_load_process. Compare to INV_SUM for cd_program=LIC.', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'INV_LIC_FACT', 'COLUMN_COUNT', 'Y', 10, 'analyst32@example.com', 'MEDIUM');

-- INV_ALLEGATION_HIST_DIM (found in SAJ script)
INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'INV_ALLEGATION_HIST_DIM', 'ROW_COUNT', 'Y', 10, 'analyst32@example.com', 'Time load >= 100368', 'MEDIUM');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'INV_ALLEGATION_HIST_DIM', 'COLUMN_COUNT', 'Y', 10, 'analyst32@example.com', 'MEDIUM');

-- Update SA_WORKLOAD_FACT to compare with SAW_SUM (found in JBF - T3C script)
-- Note: SA_WORKLOAD_FACT already exists in config, but needs comparison added
-- We'll add a separate entry for the comparison validation
UPDATE TBL_MDC_VALIDATION_CONFIG
SET COMPARE_TO_TABLE = 'SAW_SUM',
    NOTES = 'Should match SAW_SUM count exactly'
WHERE OWNER = 'CAPS' 
  AND TABLE_NAME = 'SA_WORKLOAD_FACT'
  AND VALIDATION_TYPE = 'ROW_COUNT'
  AND COMPARE_TO_TABLE IS NULL;

-- Update PP_LEGAL_CUST_FACT to compare with PP_SUM (found in JBF - T3C script)
UPDATE TBL_MDC_VALIDATION_CONFIG
SET COMPARE_TO_TABLE = 'PP_SUM',
    NOTES = 'Should match PP_SUM count exactly'
WHERE OWNER = 'CAPS' 
  AND TABLE_NAME = 'PP_LEGAL_CUST_FACT'
  AND VALIDATION_TYPE = 'ROW_COUNT'
  AND COMPARE_TO_TABLE IS NULL;

-- Update SVC_AOC_FACT to compare with SVC_SUM where CD_SVC_TYPE = 'AOC' (found in JBF - T3C script)
UPDATE TBL_MDC_VALIDATION_CONFIG
SET COMPARE_TO_TABLE = 'SVC_SUM',
    NOTES = 'Should match SVC_SUM where CD_SVC_TYPE = ''AOC'''
WHERE OWNER = 'CAPS' 
  AND TABLE_NAME = 'SVC_AOC_FACT'
  AND VALIDATION_TYPE = 'ROW_COUNT'
  AND COMPARE_TO_TABLE IS NULL;

-- AFCARS 2022 Historical/Archive Tables (found in SAJ script)
-- These are historical tables for 2022 data, grouped by nbr_federal_year and cd_federal_period
INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, GROUP_BY_COLUMNS, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'AFCARS_ADO_SUBMIT_2022', 'ROW_COUNT', 'Y', 'nbr_federal_year,cd_federal_period', 10, 'analyst33@example.com', 'Historical 2022 data table. Grouped by nbr_federal_year and cd_federal_period.', 'LOW');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'AFCARS_ADO_SUBMIT_2022', 'COLUMN_COUNT', 'Y', 10, 'analyst33@example.com', 'LOW');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, GROUP_BY_COLUMNS, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'AFCARS_FC_SUBMIT_2022', 'ROW_COUNT', 'Y', 'nbr_federal_year,cd_federal_period', 10, 'analyst33@example.com', 'Historical 2022 data table. Grouped by nbr_federal_year and cd_federal_period.', 'LOW');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'AFCARS_FC_SUBMIT_2022', 'COLUMN_COUNT', 'Y', 10, 'analyst33@example.com', 'LOW');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, GROUP_BY_COLUMNS, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'AFCARS_FC_SUBMIT_CV_2022', 'ROW_COUNT', 'Y', 'nbr_federal_year,cd_federal_period', 10, 'analyst33@example.com', 'Historical 2022 data table. Grouped by nbr_federal_year and cd_federal_period.', 'LOW');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'AFCARS_FC_SUBMIT_CV_2022', 'COLUMN_COUNT', 'Y', 10, 'analyst33@example.com', 'LOW');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, GROUP_BY_COLUMNS, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'AFCARS_FC_SUBMIT_PH_2022', 'ROW_COUNT', 'Y', 'nbr_federal_year,cd_federal_period', 10, 'analyst33@example.com', 'Historical 2022 data table. Grouped by nbr_federal_year and cd_federal_period.', 'LOW');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'AFCARS_FC_SUBMIT_PH_2022', 'COLUMN_COUNT', 'Y', 10, 'analyst33@example.com', 'LOW');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, GROUP_BY_COLUMNS, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'AFCARS_FC_SUBMIT_PP_2022', 'ROW_COUNT', 'Y', 'nbr_federal_year,cd_federal_period', 10, 'analyst33@example.com', 'Historical 2022 data table. Grouped by nbr_federal_year and cd_federal_period.', 'LOW');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'AFCARS_FC_SUBMIT_PP_2022', 'COLUMN_COUNT', 'Y', 10, 'analyst33@example.com', 'LOW');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, GROUP_BY_COLUMNS, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'AFCARS_FC_SUBMIT_PR_2022', 'ROW_COUNT', 'Y', 'nbr_federal_year,cd_federal_period', 10, 'analyst33@example.com', 'Historical 2022 data table. Grouped by nbr_federal_year and cd_federal_period.', 'LOW');

INSERT INTO TBL_MDC_VALIDATION_CONFIG (CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, THRESHOLD_PCT, EMAIL_ADDRESS, PRIORITY)
VALUES (SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'AFCARS_FC_SUBMIT_PR_2022', 'COLUMN_COUNT', 'Y', 10, 'analyst33@example.com', 'LOW');

COMMIT;

PROMPT Missing tables configuration data inserted successfully.
PROMPT
PROMPT Added tables:
PROMPT   - INV_SUM (with cd_program grouping)
PROMPT   - INV_AFC_FACT
PROMPT   - INV_APS_FACT
PROMPT   - INV_CPS_FACT
PROMPT   - INV_LIC_FACT
PROMPT   - INV_ALLEGATION_HIST_DIM
PROMPT
PROMPT Updated existing tables with comparisons:
PROMPT   - SA_WORKLOAD_FACT (compare to SAW_SUM)
PROMPT   - PP_LEGAL_CUST_FACT (compare to PP_SUM)
PROMPT   - SVC_AOC_FACT (compare to SVC_SUM where CD_SVC_TYPE = 'AOC')
PROMPT
PROMPT Added AFCARS 2022 historical tables:
PROMPT   - AFCARS_ADO_SUBMIT_2022
PROMPT   - AFCARS_FC_SUBMIT_2022
PROMPT   - AFCARS_FC_SUBMIT_CV_2022
PROMPT   - AFCARS_FC_SUBMIT_PH_2022
PROMPT   - AFCARS_FC_SUBMIT_PP_2022
PROMPT   - AFCARS_FC_SUBMIT_PR_2022

