-- ============================================================================
-- MDC Validation System - Populate Data Validation Checks
-- ============================================================================
-- Purpose: Add DATA_VALIDATION configurations for MDC_ALL source comparisons
-- Note: These are temporary validations through FY 2025
-- ============================================================================

-- SA_SUBCARE_FACT data validation
-- Should match data from MDC - query should return 0 rows
INSERT INTO TBL_MDC_VALIDATION_CONFIG (
    CONFIG_ID, OWNER, TABLE_NAME, VALIDATION_TYPE, IS_ACTIVE, 
    DATA_VALIDATION_QUERY, THRESHOLD_PCT, EMAIL_ADDRESS, NOTES, PRIORITY
)
VALUES (
    SEQ_MDC_CONFIG_ID.NEXTVAL, 'CAPS', 'SA_SUBCARE_FACT', 'DATA_VALIDATION', 'Y',
    '(
  select ''mdc'' first_col, sasb.id_time_load, sasb.dt_load_process, sasb.id_sasb_person, sasb.nm_sasb_person_full, sasb.id_sasb_stage, sasb.nm_sasb_stage_name, sasb.id_sasb_situation, sasb.id_sasb_case, sasb.cd_sasb_stage, sasb.cd_sasb_stage_type, sasb.cd_sasb_stage_rsn_closed, sasb.dt_sasb_stage_start, sasb.dt_sasb_stage_closed, sasb.id_sasb_wrkr_pr, sasb.nm_sasb_wrkr_pr_full, sasb.dt_sasb_wrkr_pr_assigned, sasb.id_sasb_wrkr_se_elig, sasb.id_sasb_workload_unit, sasb.nbr_sasb_workload_unit, sasb.cd_sasb_workload_region, sasb.id_sasb_supv_stg_resp_unit, sasb.nbr_sasb_supv_stg_resp_unit, sasb.cd_sasb_supv_stg_resp_region, sasb.nbr_sasb_person_dhs_client_nbr, sasb.nbr_sasb_person_social_sec_nbr, sasb.nbr_sasb_person_age_yrs, sasb.nbr_sasb_person_age_mos, sasb.cd_sasb_person_sex, sasb.cd_sasb_ethnicity, sasb.id_sasb_stage_prior, sasb.cd_sasb_stage_prior, sasb.id_sasb_chplan_event, sasb.cd_sasb_chplan_perm_goal, sasb.cd_sasb_chplan_plan_type, sasb.dt_sasb_chplan_approval, sasb.id_sasb_aloc_event, sasb.cd_sasb_aloc, sasb.dt_sasb_aloc_start, sasb.dt_sasb_aloc_end, sasb.id_sasb_bloc_event, sasb.cd_sasb_bloc, sasb.dt_sasb_bloc_start, sasb.dt_sasb_bloc_end, sasb.dt_sasb_sup_apprvd_hsegh, sasb.ind_sasb_ret_sub_aft_own_hm, sasb.id_sasb_legstat_event, sasb.dt_sasb_legstat_status, sasb.cd_sasb_legstat_status, sasb.cd_sasb_legstat_county, sasb.cd_sasb_legstat_region, sasb.dt_sasb_profassmt_sixmodent, sasb.dt_sasb_profassmt_othdent, sasb.dt_sasb_profassmt_phys_exam, sasb.dt_sasb_profassmt_annual_med, sasb.id_sasb_elig_event, sasb.cd_sasb_elig_selected, sasb.cd_sasb_elig_med_elig_group, sasb.dt_sasb_elig_start, sasb.dt_sasb_elig_end, sasb.id_sasb_rsvcpkg_event, sasb.cd_sasb_rsvcpkg, sasb.dt_sasb_rsvcpkg_start, sasb.dt_sasb_rsvcpkg_end, sasb.cd_sasb_rsvcpkg_end_rsn, sasb.id_sasb_ssvcpkg_person_svc_pkg, sasb.id_sasb_ssvcpkg_event, sasb.cd_sasb_ssvcpkg, sasb.dt_sasb_ssvcpkg_start, sasb.dt_sasb_ssvcpkg_end, sasb.cd_sasb_ssvcpkg_end_rsn, sasb.id_sasb_case, sasb.id_sasb_stage, sasb.ind_sasb_floc_match
  from caps.sa_subcare_fact sasb
       inner join caps.time_dim td on td.id_time_load between (select distinct b.id_time_load from caps.time_dim b where to_char(b.dt_time_first_day_mo,''YYYYMM'') = to_char(add_months(sysdate, -3),''YYYYMM'')) and (select distinct b.id_time_load from caps.time_dim b where to_char(b.dt_time_first_day_mo,''YYYYMM'') = to_char(add_months(sysdate, -1),''YYYYMM''))
                                  and td.dt_time_last_day_mo >= sasb.dt_sasb_stage_start
       left join get_latest_rcmndd_svc_pkg glrsp on glrsp.id_person = sasb.id_sasb_person and glrsp.id_time_load = sasb.id_time_load
       left join get_latest_slctd_svc_pkg glssp on glssp.id_person = sasb.id_sasb_person and glssp.id_time_load = sasb.id_time_load
  where sasb.id_time_load between (select distinct b.id_time_load from caps.time_dim b where to_char(b.dt_time_first_day_mo,''YYYYMM'') = to_char(add_months(sysdate, -3),''YYYYMM'')) and (select distinct b.id_time_load from caps.time_dim b where to_char(b.dt_time_first_day_mo,''YYYYMM'') = to_char(add_months(sysdate, -1),''YYYYMM''))
    minus
  select ''mdc'' first_col, sasb.id_time_load, sasb.dt_load_process, sasb.id_sasb_person, sasb.nm_sasb_person_full, sasb.id_sasb_stage, sasb.nm_sasb_stage_name, sasb.id_sasb_situation, sasb.id_sasb_case, sasb.cd_sasb_stage, sasb.cd_sasb_stage_type, sasb.cd_sasb_stage_rsn_closed, sasb.dt_sasb_stage_start, sasb.dt_sasb_stage_closed, sasb.id_sasb_wrkr_pr, sasb.nm_sasb_wrkr_pr_full, sasb.dt_sasb_wrkr_pr_assigned, sasb.id_sasb_wrkr_se_elig, sasb.id_sasb_workload_unit, sasb.nbr_sasb_workload_unit, sasb.cd_sasb_workload_region, sasb.id_sasb_supv_stg_resp_unit, sasb.nbr_sasb_supv_stg_resp_unit, sasb.cd_sasb_supv_stg_resp_region, sasb.nbr_sasb_person_dhs_client_nbr, sasb.nbr_sasb_person_social_sec_nbr, sasb.nbr_sasb_person_age_yrs, sasb.nbr_sasb_person_age_mos, sasb.cd_sasb_person_sex, sasb.cd_sasb_ethnicity, sasb.id_sasb_stage_prior, sasb.cd_sasb_stage_prior, sasb.id_sasb_chplan_event, sasb.cd_sasb_chplan_perm_goal, sasb.cd_sasb_chplan_plan_type, sasb.dt_sasb_chplan_approval, sasb.id_sasb_aloc_event, sasb.cd_sasb_aloc, sasb.dt_sasb_aloc_start, sasb.dt_sasb_aloc_end, sasb.id_sasb_bloc_event, sasb.cd_sasb_bloc, sasb.dt_sasb_bloc_start, sasb.dt_sasb_bloc_end, sasb.dt_sasb_sup_apprvd_hsegh, sasb.ind_sasb_ret_sub_aft_own_hm, sasb.id_sasb_legstat_event, sasb.dt_sasb_legstat_status, sasb.cd_sasb_legstat_status, sasb.cd_sasb_legstat_county, sasb.cd_sasb_legstat_region, sasb.dt_sasb_profassmt_sixmodent, sasb.dt_sasb_profassmt_othdent, sasb.dt_sasb_profassmt_phys_exam, sasb.dt_sasb_profassmt_annual_med, sasb.id_sasb_elig_event, sasb.cd_sasb_elig_selected, sasb.cd_sasb_elig_med_elig_group, sasb.dt_sasb_elig_start, sasb.dt_sasb_elig_end, sasb.id_sasb_rsvcpkg_event, sasb.cd_sasb_rsvcpkg, sasb.dt_sasb_rsvcpkg_start, sasb.dt_sasb_rsvcpkg_end, sasb.cd_sasb_rsvcpkg_end_rsn, sasb.id_sasb_ssvcpkg_person_svc_pkg, sasb.id_sasb_ssvcpkg_event, sasb.cd_sasb_ssvcpkg, sasb.dt_sasb_ssvcpkg_start, sasb.dt_sasb_ssvcpkg_end, sasb.cd_sasb_ssvcpkg_end_rsn, sasb.id_sasb_case, sasb.id_sasb_stage, sasb.ind_sasb_floc_match
  from caps.sa_subcare_fact sasb
       inner join caps.time_dim td on td.id_time_load between (select distinct b.id_time_load from caps.time_dim b where to_char(b.dt_time_first_day_mo,''YYYYMM'') = to_char(add_months(sysdate, -3),''YYYYMM'')) and (select distinct b.id_time_load from caps.time_dim b where to_char(b.dt_time_first_day_mo,''YYYYMM'') = to_char(add_months(sysdate, -1),''YYYYMM''))
                                  and td.dt_time_last_day_mo >= sasb.dt_sasb_stage_start
       left join get_latest_rcmndd_svc_pkg glrsp on glrsp.id_person = sasb.id_sasb_person and glrsp.id_time_load = sasb.id_time_load
       left join get_latest_slctd_svc_pkg glssp on glssp.id_person = sasb.id_sasb_person and glssp.id_time_load = sasb.id_time_load
  where sasb.id_time_load between (select distinct b.id_time_load from caps.time_dim b where to_char(b.dt_time_first_day_mo,''YYYYMM'') = to_char(add_months(sysdate, -3),''YYYYMM'')) and (select distinct b.id_time_load from caps.time_dim b where to_char(b.dt_time_first_day_mo,''YYYYMM'') = to_char(add_months(sysdate, -1),''YYYYMM''))
)
union all
(
  select ''ware'' first_col, sasb.id_time_load, sasb.dt_load_process, sasb.id_sasb_person, sasb.nm_sasb_person_full, sasb.id_sasb_stage, sasb.nm_sasb_stage_name, sasb.id_sasb_situation, sasb.id_sasb_case, sasb.cd_sasb_stage, sasb.cd_sasb_stage_type, sasb.cd_sasb_stage_rsn_closed, sasb.dt_sasb_stage_start, sasb.dt_sasb_stage_closed, sasb.id_sasb_wrkr_pr, sasb.nm_sasb_wrkr_pr_full, sasb.dt_sasb_wrkr_pr_assigned, sasb.id_sasb_wrkr_se_elig, sasb.id_sasb_workload_unit, sasb.nbr_sasb_workload_unit, sasb.cd_sasb_workload_region, sasb.id_sasb_supv_stg_resp_unit, sasb.nbr_sasb_supv_stg_resp_unit, sasb.cd_sasb_supv_stg_resp_region, sasb.nbr_sasb_person_dhs_client_nbr, sasb.nbr_sasb_person_social_sec_nbr, sasb.nbr_sasb_person_age_yrs, sasb.nbr_sasb_person_age_mos, sasb.cd_sasb_person_sex, sasb.cd_sasb_ethnicity, sasb.id_sasb_stage_prior, sasb.cd_sasb_stage_prior, sasb.id_sasb_chplan_event, sasb.cd_sasb_chplan_perm_goal, sasb.cd_sasb_chplan_plan_type, sasb.dt_sasb_chplan_approval, sasb.id_sasb_aloc_event, sasb.cd_sasb_aloc, sasb.dt_sasb_aloc_start, sasb.dt_sasb_aloc_end, sasb.id_sasb_bloc_event, sasb.cd_sasb_bloc, sasb.dt_sasb_bloc_start, sasb.dt_sasb_bloc_end, sasb.dt_sasb_sup_apprvd_hsegh, sasb.ind_sasb_ret_sub_aft_own_hm, sasb.id_sasb_legstat_event, sasb.dt_sasb_legstat_status, sasb.cd_sasb_legstat_status, sasb.cd_sasb_legstat_county, sasb.cd_sasb_legstat_region, sasb.dt_sasb_profassmt_sixmodent, sasb.dt_sasb_profassmt_othdent, sasb.dt_sasb_profassmt_phys_exam, sasb.dt_sasb_profassmt_annual_med, sasb.id_sasb_elig_event, sasb.cd_sasb_elig_selected, sasb.cd_sasb_elig_med_elig_group, sasb.dt_sasb_elig_start, sasb.dt_sasb_elig_end, sasb.id_sasb_rsvcpkg_event, sasb.cd_sasb_rsvcpkg, sasb.dt_sasb_rsvcpkg_start, sasb.dt_sasb_rsvcpkg_end, sasb.cd_sasb_rsvcpkg_end_rsn, sasb.id_sasb_ssvcpkg_person_svc_pkg, sasb.id_sasb_ssvcpkg_event, sasb.cd_sasb_ssvcpkg, sasb.dt_sasb_ssvcpkg_start, sasb.dt_sasb_ssvcpkg_end, sasb.cd_sasb_ssvcpkg_end_rsn, sasb.id_sasb_case, sasb.id_sasb_stage, sasb.ind_sasb_floc_match
  from caps.sa_subcare_fact sasb
       inner join caps.time_dim td on td.id_time_load between (select distinct b.id_time_load from caps.time_dim b where to_char(b.dt_time_first_day_mo,''YYYYMM'') = to_char(add_months(sysdate, -3),''YYYYMM'')) and (select distinct b.id_time_load from caps.time_dim b where to_char(b.dt_time_first_day_mo,''YYYYMM'') = to_char(add_months(sysdate, -1),''YYYYMM''))
                                  and td.dt_time_last_day_mo >= sasb.dt_sasb_stage_start
       left join get_latest_rcmndd_svc_pkg glrsp on glrsp.id_person = sasb.id_sasb_person and glrsp.id_time_load = sasb.id_time_load
       left join get_latest_slctd_svc_pkg glssp on glssp.id_person = sasb.id_sasb_person and glssp.id_time_load = sasb.id_time_load
  where sasb.id_time_load between (select distinct b.id_time_load from caps.time_dim b where to_char(b.dt_time_first_day_mo,''YYYYMM'') = to_char(add_months(sysdate, -3),''YYYYMM'')) and (select distinct b.id_time_load from caps.time_dim b where to_char(b.dt_time_first_day_mo,''YYYYMM'') = to_char(add_months(sysdate, -1),''YYYYMM''))
    minus
  select ''ware'' first_col, sasb.id_time_load, sasb.dt_load_process, sasb.id_sasb_person, sasb.nm_sasb_person_full, sasb.id_sasb_stage, sasb.nm_sasb_stage_name, sasb.id_sasb_situation, sasb.id_sasb_case, sasb.cd_sasb_stage, sasb.cd_sasb_stage_type, sasb.cd_sasb_stage_rsn_closed, sasb.dt_sasb_stage_start, sasb.dt_sasb_stage_closed, sasb.id_sasb_wrkr_pr, sasb.nm_sasb_wrkr_pr_full, sasb.dt_sasb_wrkr_pr_assigned, sasb.id_sasb_wrkr_se_elig, sasb.id_sasb_workload_unit, sasb.nbr_sasb_workload_unit, sasb.cd_sasb_workload_region, sasb.id_sasb_supv_stg_resp_unit, sasb.nbr_sasb_supv_stg_resp_unit, sasb.cd_sasb_supv_stg_resp_region, sasb.nbr_sasb_person_dhs_client_nbr, sasb.nbr_sasb_person_social_sec_nbr, sasb.nbr_sasb_person_age_yrs, sasb.nbr_sasb_person_age_mos, sasb.cd_sasb_person_sex, sasb.cd_sasb_ethnicity, sasb.id_sasb_stage_prior, sasb.cd_sasb_stage_prior, sasb.id_sasb_chplan_event, sasb.cd_sasb_chplan_perm_goal, sasb.cd_sasb_chplan_plan_type, sasb.dt_sasb_chplan_approval, sasb.id_sasb_aloc_event, sasb.cd_sasb_aloc, sasb.dt_sasb_aloc_start, sasb.dt_sasb_aloc_end, sasb.id_sasb_bloc_event, sasb.cd_sasb_bloc, sasb.dt_sasb_bloc_start, sasb.dt_sasb_bloc_end, sasb.dt_sasb_sup_apprvd_hsegh, sasb.ind_sasb_ret_sub_aft_own_hm, sasb.id_sasb_legstat_event, sasb.dt_sasb_legstat_status, sasb.cd_sasb_legstat_status, sasb.cd_sasb_legstat_county, sasb.cd_sasb_legstat_region, sasb.dt_sasb_profassmt_sixmodent, sasb.dt_sasb_profassmt_othdent, sasb.dt_sasb_profassmt_phys_exam, sasb.dt_sasb_profassmt_annual_med, sasb.id_sasb_elig_event, sasb.cd_sasb_elig_selected, sasb.cd_sasb_elig_med_elig_group, sasb.dt_sasb_elig_start, sasb.dt_sasb_elig_end, sasb.id_sasb_rsvcpkg_event, sasb.cd_sasb_rsvcpkg, sasb.dt_sasb_rsvcpkg_start, sasb.dt_sasb_rsvcpkg_end, sasb.cd_sasb_rsvcpkg_end_rsn, sasb.id_sasb_ssvcpkg_person_svc_pkg, sasb.id_sasb_ssvcpkg_event, sasb.cd_sasb_ssvcpkg, sasb.dt_sasb_ssvcpkg_start, sasb.dt_sasb_ssvcpkg_end, sasb.cd_sasb_ssvcpkg_end_rsn, sasb.id_sasb_case, sasb.id_sasb_stage, sasb.ind_sasb_floc_match
  from caps.sa_subcare_fact sasb
       inner join caps.time_dim td on td.id_time_load between (select distinct b.id_time_load from caps.time_dim b where to_char(b.dt_time_first_day_mo,''YYYYMM'') = to_char(add_months(sysdate, -3),''YYYYMM'')) and (select distinct b.id_time_load from caps.time_dim b where to_char(b.dt_time_first_day_mo,''YYYYMM'') = to_char(add_months(sysdate, -1),''YYYYMM''))
                                  and td.dt_time_last_day_mo >= sasb.dt_sasb_stage_start
       left join get_latest_rcmndd_svc_pkg glrsp on glrsp.id_person = sasb.id_sasb_person and glrsp.id_time_load = sasb.id_time_load
       left join get_latest_slctd_svc_pkg glssp on glssp.id_person = sasb.id_sasb_person and glssp.id_time_load = sasb.id_time_load
  where sasb.id_time_load between (select distinct b.id_time_load from caps.time_dim b where to_char(b.dt_time_first_day_mo,''YYYYMM'') = to_char(add_months(sysdate, -3),''YYYYMM'')) and (select distinct b.id_time_load from caps.time_dim b where to_char(b.dt_time_first_day_mo,''YYYYMM'') = to_char(add_months(sysdate, -1),''YYYYMM''))
)',
    10, 'analyst15@example.com', 
    'Data validation check - should return 0 rows if data matches MDC source. Temporary validation through FY 2025.', 
    'MEDIUM'
);

-- Note: The above query is very complex and uses CTEs. For production, these queries should be stored
-- in a separate table or file and referenced. For now, this is a placeholder showing the structure.
-- Full implementation would require extracting the actual queries from the manual scripts.

COMMIT;

PROMPT Data validation configurations added (placeholder - full queries need to be extracted from manual scripts).

